annotations:
  nginx.ingress.kubernetes.io/configuration-snippet :  |
    add_header X-Frame-Options "sameorigin";
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy 'same-origin';
    add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header Clear-Site-Data "cookies";
    add_header Content-Security-Policy: "default-src 'self';";
    add_header X-Permitted-Cross-Domain-Policies master-only;