apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  # or ReplicaSet
    name: my-app-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 200Mi  # Target average memory usage
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70  # Target CPU utilization percentage
